import React from 'react';
import { useTranslation } from 'react-i18next';
import type { ForensicEvidence } from '@/types/evidence';
import './TraceAnalysisViewer.css';

type TraceEvidence = Extract<ForensicEvidence, { sub_type: 'trace_analysis' }>;

interface TraceAnalysisViewerProps {
  evidence: TraceEvidence;
}

const TraceAnalysisViewer: React.FC<TraceAnalysisViewerProps> = ({ evidence }) => {
  const { t } = useTranslation();
  const { metadata } = evidence;

  // Deterministically generate a jagged mass spectrometry graph based on the Evidence ID
  const generatePeaks = (seed: number) => {
    let points = "0,100 ";
    for (let i = 1; i <= 20; i++) {
      const x = i * 5;
      const isMajorPeak = (seed * i) % 7 === 0;
      const y = isMajorPeak ? 10 + ((seed * i) % 20) : 75 + ((seed * i) % 20);
      points += `${x},${y} `;
    }
    points += "100,100";
    return points;
  };

  return (
    <div className="forensic-preview trace-paper">
      <div className="trace-header">
        <div className="trace-agency">{t('pages.gameRoom.evidence.viewers.traceAnalysis.advancedLab')}</div>
        <h2 className="trace-title">{t('pages.gameRoom.evidence.viewers.traceAnalysis.massSpec')}</h2>
      </div>

      <div className="trace-meta">
        <div><span className="trace-label">{t('pages.gameRoom.evidence.viewers.traceAnalysis.sampleId')}</span> EX-{evidence.id.toString().padStart(3, '0')}</div>
        <div><span className="trace-label">{t('pages.gameRoom.evidence.viewers.traceAnalysis.scanDate')}</span> {new Date().toLocaleDateString()}</div>
      </div>

      <div className="trace-graph-box">
        <h4 className="trace-graph-title">{t('pages.gameRoom.evidence.viewers.traceAnalysis.spectralChart')}</h4>
        <svg viewBox="0 0 100 100" className="trace-graph" preserveAspectRatio="none">
          {/* Grid Lines */}
          <line x1="0" y1="25" x2="100" y2="25" className="trace-grid-line" />
          <line x1="0" y1="50" x2="100" y2="50" className="trace-grid-line" />
          <line x1="0" y1="75" x2="100" y2="75" className="trace-grid-line" />

          {/* Data Lines */}
          <polyline points={generatePeaks(evidence.id)} className="trace-data-line primary-line" />
          <polyline points={generatePeaks(evidence.id + 1)} className="trace-data-line secondary-line" />
        </svg>
        <div className="trace-axis-labels">
          <span>{t('pages.gameRoom.evidence.viewers.traceAnalysis.mzRatio')}</span>
          <span>{t('pages.gameRoom.evidence.viewers.traceAnalysis.relativeAbundance')}</span>
        </div>
      </div>

      <div className="trace-results">
        <div className="trace-result-row">
          <span className="trace-label">{t('pages.gameRoom.evidence.viewers.traceAnalysis.materialComp')}</span>
          <span className="trace-value">{metadata.material_type}</span>
        </div>
        <div className="trace-result-row match-row">
          <span className="trace-label">{t('pages.gameRoom.evidence.viewers.traceAnalysis.originSource')}</span>
          <span className="trace-value source-match">{metadata.origin_source}</span>
        </div>
      </div>

      <div className="trace-footer">
        <span>{t('pages.gameRoom.evidence.viewers.traceAnalysis.analysisComplete')}</span>
        <span className="trace-signature">{t('pages.gameRoom.evidence.viewers.traceAnalysis.autoGenerated')}</span>
      </div>
    </div>
  );
};

export default TraceAnalysisViewer;